default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Zealot"
  lane :beta do
    gradle(task: "clean assembleBeta")

    zealot(
      endpoint: ENV["ZEALOT_ENDPOINT"],
      token: ENV["ZEALOT_TOKEN"],
      channel_key: ENV["ZEALOT_BETA_CHANNEL_KEY"],
      changelog: changelog_from_git_commits(commits_count: 10, pretty: "- %s"),
      release_type: "beta",
      branch: git_branch,
      git_commit: last_git_commit[:commit_hash]
    )
  end

  desc "Deploy a new production version to Zealot"
  lane :production do
    gradle(task: "clean assembleRelease")

    zealot(
      endpoint: ENV["ZEALOT_ENDPOINT"],
      token: ENV["ZEALOT_TOKEN"],
      channel_key: ENV["ZEALOT_PROD_CHANNEL_KEY"],
      changelog: changelog_from_git_commits(commits_count: 10, pretty: "- %s"),
      release_type: "release",
      branch: git_branch,
      git_commit: last_git_commit[:commit_hash]
    )
  end
end
